config/routes.rb
Rails.application.routes.draw do
  resources :books
  # get 'homes/top' 以下に書き換え
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

def create
  @book = Book.new(book_params)
  if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    @books = Book.all # 保存後に最新の本の一覧を取得する
  else
    @books = Book.all
    render :index
  end
end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <div>
    <%= flash[:notice] %>
  </div>
<% end %>

<h1><strong>Editing Book</strong></h1>

<% if @book.errors.any? %>
   <%= @book.errors.count %> error.
  <div class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

  <%= link_to "Show", book_path %>
  <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <div>
    <%= flash[:notice] %>
  </div>
<% end %>

<div>
  <%= flash[:alert] %>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
     <!-- 本の一覧を表示する部分 -->


  <table>
      <td colspan="2">
        <h2>New book</h2>
        <% if @book.errors.any? %>
          <%= @book.errors.count %> errors prohibited this book from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </td>
  </table>
        <%= form_with model: @book do |f| %>

        <tr>
          <td><h4>Title</h4></td>
          <td><%= f.text_field :title %></td>
        </tr>

        <tr>
          <td><h4>Body</h4></td>
          <td><%= f.text_area :body %></td>
        </tr>

        <p>
            <%= f.submit 'Create Book' %>
        </p>
        <% end %>

app/views/books/new.html.erb
<div>
  <%= flash[:notice] %>
</div>

<h1><strong>New book</strong></h1>

<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div>
    <%= flash[:notice] %>
  </div>
<% end %>

<p>Title: <%= @book.title %></p>
<p>Body: <%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/start.html.erb
<p>
  <a href="/books">start</a>
</p>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
      ようこそ<strong>Bookers</strong>へ！
    </h1>
    <br>
    <p>
      <strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
    </p><br>
    <p>印象を共有し交換することができます</p>
 <a href="/books">start</a>
</div>

<!-- 元の記述 <p>Find me in app/views/homes/top.html.erb</p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>